apiVersion: v1
items:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: crud-config
  data: 
    redis.host: "redis.redis-ha.svc"
    redis.port: "6379"
    redis.db: "0"
  
- apiVersion: v1
  kind: Secret
  metadata:
    name: crud-secret
  data:   
    password: UEBzc3cwcmQ=
    
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      app: crud-build
      name: crud
    name: crud-build
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: crud:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        uri: https://github.com/femiosinowo/test-CRUD-flask.git
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: python-35-centos7:v3.5
          namespace: openshift
      type: Source
    triggers: []
  status:
    lastVersion: 0
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      build: crud
    name: crud
  status:
    dockerImageRepository: ""
	
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    generation: 1
    labels:
      app: crud
      crud: "true"
    name: crud
  spec:
    replicas: 1
    selector:
      app: crud
      crud: "true"
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: crud
          crud: "true"
      spec:
        containers:
        - env:
          - name: REDIS_HOST
            valueFrom: 
              configMapKeyRef: 
                name: crud-config
                key: redis.host
          - name: REDIS_PORT
            valueFrom: 
              configMapKeyRef: 
                name: crud-config
                key: redis.port
          - name: REDIS_DB
            valueFrom: 
              configMapKeyRef: 
                name: crud-config
                key: redis.db
          - name: REDIS_PASSWORD
            valueFrom: 
              secretKeyRef: 
                name: crud-secret
                key: password
            image: ' '
          imagePullPolicy: Always
          name: crud
          ports:
          - containerPort: 5000
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          #volumeMounts:
          #- mountPath: /redis-master-data
          #  name: data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
        #volumes:
        #- emptyDir: {}
        #  name: data
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - crud
        from:
          kind: ImageStreamTag
          name: crud:latest
      type: ImageChange
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      name: crud
      role: service
    name: crud
  spec:
    ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
    selector:
      app: "crud"
    sessionAffinity: None
    type: ClusterIP
	
	
kind: List
metadata: {}