FROM centos/python-35-centos7
MAINTAINER Femi Osinowo "femiosinowo@gmail.com"
#RUN apt-get update -y
#RUN apt-get install -y python-pip python-dev build-essential
ENV LOGNAME=ipython
ENV USER=ipython
WORKDIR /src

COPY . /src

RUN pip install -r requirements.txt
#ENTRYPOINT ["python"]
#CMD ["app.py"]
